name: Generate firebaseConfig.json

on:
  push:
    branches:
      - main

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Generar archivo de entorno para producción
      - name: Generate firebaseConfig.json
        run: |
          echo '{
            "projectId": "${{ secrets.PROJECT_ID }}",
            "databaseURL": "${{ secrets.DATABASEURL }}",
            "clientEmail": "${{ secrets.CLIENT_EMAIL }}",
            "privateKey": "${{ secrets.PRIVATE_KEY }}"
          }' > ./assets/firebaseConfig.json
